'use server';

import { signIn } from '@/auth';
import { AuthError } from 'next-auth';
import { z } from 'zod';
import bcrypt from 'bcryptjs';
import { supabase } from '@/lib/supabase';

const CredentialsSchema = z.object({
    username: z.string().min(3, 'Username must be at least 3 characters.'),
    password: z.string().min(6, 'Password must be at least 6 characters.'),
});

export async function authenticate(
    prevState: string | undefined,
    formData: FormData,
) {
    try {
        formData.append("redirectTo", "/dashboard");
        await signIn('credentials', formData);
    } catch (error) {
        if (error instanceof AuthError) {
            switch (error.type) {
                case 'CredentialsSignin':
                    return 'Invalid credentials.';
                default:
                    return 'Something went wrong.';
            }
        }
        throw error;
    }
}

export async function register(
    prevState: string | undefined,
    formData: FormData,
) {
    const data = Object.fromEntries(formData);
    const parsed = CredentialsSchema.safeParse(data);

    if (!parsed.success) {
        return 'Invalid input: ' + parsed.error.issues.map(e => e.message).join(', ');
    }

    const { username, password } = parsed.data;

    // Check if user exists
    const { data: existingUser } = await supabase
        .from('Users')
        .select('id')
        .eq('username', username)
        .single();

    if (existingUser) {
        return 'Username already taken.';
    }

    const hashedPassword = await bcrypt.hash(password, 10);
    // userId is generated by Postgres (DEFAULT gen_random_uuid())
    const publicKey = formData.get('publicKey') as string;

    try {
        const { error } = await supabase.from('Users').insert({
            username,
            password_hash: hashedPassword,
            password_hash: hashedPassword,
            public_key: publicKey,
            encrypted_vault: formData.get('encryptedVault') as string,
            vault_salt: formData.get('vaultSalt') as string
        });

        if (error) throw error;
    } catch (error) {
        console.error("Supabase Error:", error);
        return 'Database error: Failed to create user.';
    }

    // Auto login after registration
    try {
        formData.append("redirectTo", "/dashboard");
        await signIn('credentials', formData);
    } catch (error) {
        if (error instanceof AuthError) {
            switch (error.type) {
                case 'CredentialsSignin':
                    return 'Registration successful, but login failed.';
                default:
                    return 'Something went wrong.';
            }
        }
        throw error;
    }
}
