'use server';

import { signIn, auth } from '@/auth';
import { AuthError } from 'next-auth';
import { isRedirectError } from 'next/dist/client/components/redirect-error';
import { z } from 'zod';
import bcrypt from 'bcryptjs';
import crypto from 'node:crypto';
import { supabaseAdmin } from '@/lib/supabase';
import { rateLimit } from '@/lib/rate-limit';
import { logError } from '@/lib/log';
import { getClientIp } from '@/lib/request-meta';

// OWASP 2023+ recommends bcrypt cost factor >= 12.
const BCRYPT_COST = 12;

const CredentialsSchema = z.object({
    username: z.string().min(3, 'Username must be at least 3 characters.'),
    password: z.string().min(12, 'Password must be at least 12 characters.'),
});

export async function authenticate(
    prevState: string | undefined,
    formData: FormData,
) {
    try {
        await signIn('credentials', {
            username: formData.get('username'),
            password: formData.get('password'),
            redirect: false,
        });
        return null; // Success
    } catch (error) {
        if (isRedirectError(error)) {
            // signIn succeeded but threw a redirect — session cookie is set
            return null;
        }
        if (error instanceof AuthError) {
            switch (error.type) {
                case 'CredentialsSignin':
                    return 'Invalid credentials.';
                default:
                    return 'Something went wrong.';
            }
        }
        return 'Something went wrong.';
    }
}

export async function register(
    prevState: string | undefined,
    formData: FormData,
) {
    // Per-IP throttle on registration — bot-driven account creation is the
    // most likely abuse vector here. 5 successful registrations per IP per
    // hour is plenty for legit users (NAT/shared networks excluded; bump if
    // we see false positives).
    const ip = await getClientIp();
    {
        const { allowed } = rateLimit(`register-ip:${ip}`, 5, 60 * 60 * 1000);
        if (!allowed) return 'Too many registrations from this network. Please try again later.';
    }

    const data = Object.fromEntries(formData);
    const parsed = CredentialsSchema.safeParse(data);

    if (!parsed.success) {
        return 'Invalid input: ' + parsed.error.issues.map(e => e.message).join(', ');
    }

    const { username, password } = parsed.data;

    // Check if user exists
    const { data: existingUser } = await supabaseAdmin
        .from('Users')
        .select('id')
        .eq('username', username)
        .single();

    if (existingUser) {
        return 'Username already taken.';
    }

    const hashedPassword = await bcrypt.hash(password, BCRYPT_COST);
    // userId is generated by Postgres (DEFAULT gen_random_uuid())
    const publicKey = formData.get('publicKey') as string;
    const encryptedVault = formData.get('encryptedVault') as string;
    const vaultSalt = formData.get('vaultSalt') as string;

    // Validate cryptographic material
    if (publicKey) {
        try {
            const parsed = JSON.parse(publicKey);
            if (parsed.kty !== 'RSA' || !parsed.n || !parsed.e) {
                return 'Invalid public key format.';
            }
        } catch {
            return 'Invalid public key format.';
        }
    }
    if (encryptedVault && encryptedVault.length > 50_000) return 'Vault data too large.';
    if (vaultSalt && vaultSalt.length > 200) return 'Vault salt too large.';

    try {
        const { error } = await supabaseAdmin.from('Users').insert({
            username,
            password_hash: hashedPassword,
            public_key: publicKey,
            encrypted_vault: encryptedVault,
            vault_salt: vaultSalt
        });

        if (error) throw error;
    } catch (error) {
        logError('register: insert user failed', error);
        return 'Database error: Failed to create user.';
    }

    // Return null = success. Client will handle signIn separately.
    return null;
}

// --- Profile Actions ---

export async function getUserProfileAction() {
    const session = await auth();
    if (!session?.user?.id) return { error: "Not authenticated" };

    const { data, error } = await supabaseAdmin
        .from('Users')
        .select('username, created_at, location, preferred_contact')
        .eq('id', session.user.id)
        .single();

    if (error || !data) return { error: "Failed to load profile" };
    return { profile: data };
}

export async function updateUserProfileAction(location: string, preferredContact: string) {
    const session = await auth();
    if (!session?.user?.id) return { error: "Not authenticated" };

    const { error } = await supabaseAdmin
        .from('Users')
        .update({
            location: location || null,
            preferred_contact: preferredContact || null,
        })
        .eq('id', session.user.id);

    if (error) return { error: "Failed to update profile" };
    return { success: true };
}

export async function deleteAccountAction() {
    const session = await auth();
    if (!session?.user?.id) return { error: "Not authenticated" };

    const { error } = await supabaseAdmin
        .from('Users')
        .delete()
        .eq('id', session.user.id);

    if (error) {
        logError('deleteAccount failed', error);
        return { error: "Failed to delete account" };
    }
    return { success: true };
}

/**
 * Look up the on-server vault for a given username, used by the client to
 * derive the user's private key from their password.
 *
 * Enumeration resistance (C6): the response shape is identical for known
 * and unknown usernames. For unknown users we synthesize a deterministic
 * decoy vault from HMAC(AUTH_SECRET, username) so:
 *
 *   - Probing the same username twice returns the same blob (a rotating
 *     blob would itself signal "fake").
 *   - Decryption fails with the same error path as a wrong password against
 *     a real vault, so the attacker cannot distinguish "user does not exist"
 *     from "user exists but wrong password" without a successful login.
 *
 * Per-IP and per-username rate limits further slow any enumeration attempt.
 */
export async function getVaultAction(username: string) {
    const ip = await getClientIp();

    // Per-IP limit catches the "probe many usernames" pattern that a per-username
    // limit alone misses.
    {
        const { allowed } = rateLimit(`vault-ip:${ip}`, 60, 60_000);
        if (!allowed) return decoyVault(username);
    }
    // Per-username limit: 10 per minute (existing).
    {
        const { allowed } = rateLimit(`vault:${username}`, 10, 60_000);
        if (!allowed) return decoyVault(username);
    }

    const { data } = await supabaseAdmin
        .from('Users')
        .select('encrypted_vault, vault_salt, public_key')
        .eq('username', username)
        .single();

    if (!data || !data.encrypted_vault || !data.vault_salt) {
        return decoyVault(username);
    }

    return {
        encryptedVault: data.encrypted_vault,
        vaultSalt: data.vault_salt,
        publicKey: data.public_key,
    };
}

/**
 * Deterministic decoy vault for an unknown username. Same shape as a real
 * vault response so enumeration via response shape, size, or timing is
 * harder. Decryption will fail downstream with the same error as a real
 * wrong-password attempt.
 */
function decoyVault(username: string): {
    encryptedVault: string;
    vaultSalt: string;
    publicKey: null;
} {
    const secret = process.env.AUTH_SECRET || 'uunn-decoy-fallback-secret';
    const seed = crypto.createHmac('sha256', secret).update(`vault:${username}`).digest();

    // Sizes mirror a real v2 vault for an RSA-2048 private key.
    // (~1700-byte JWK → after PBKDF2/AES-GCM + JSON envelope + base64 ≈ 2400 chars)
    const fakeIv = seed.subarray(0, 12).toString('base64');
    const ctLen = 2400; // bytes of synthetic ciphertext base64
    const ct = crypto
        .createHmac('sha256', secret)
        .update(`ct:${username}`)
        .digest()
        .toString('base64')
        .repeat(40)
        .slice(0, ctLen);
    const envelope = JSON.stringify({
        v: 2,
        kdf: 'PBKDF2-SHA256',
        iter: 600_000,
        iv: fakeIv,
        ct,
    });
    const encryptedVault = Buffer.from(envelope, 'utf-8').toString('base64');
    const vaultSalt = seed.subarray(12, 28).toString('base64');

    return { encryptedVault, vaultSalt, publicKey: null };
}

/**
 * Replace the current user's vault. Used for lazy upgrade from v1 to v2
 * format on first successful login post-deploy. The session cookie alone
 * authorizes this — the caller has already proven knowledge of the
 * password by deriving the new vault from it.
 */
export async function upgradeVaultAction(encryptedVault: string, vaultSalt: string) {
    const session = await auth();
    if (!session?.user?.id) return { error: 'Not authenticated' };

    if (typeof encryptedVault !== 'string' || encryptedVault.length === 0 || encryptedVault.length > 50_000) {
        return { error: 'Invalid vault' };
    }
    if (typeof vaultSalt !== 'string' || vaultSalt.length === 0 || vaultSalt.length > 200) {
        return { error: 'Invalid salt' };
    }

    const { error } = await supabaseAdmin
        .from('Users')
        .update({ encrypted_vault: encryptedVault, vault_salt: vaultSalt })
        .eq('id', session.user.id);

    if (error) {
        logError('upgradeVault failed', error);
        return { error: 'Failed to upgrade vault' };
    }
    return { success: true };
}
