'use server';

import { signIn, auth } from '@/auth';
import { AuthError } from 'next-auth';
import { isRedirectError } from 'next/dist/client/components/redirect-error';
import { z } from 'zod';
import bcrypt from 'bcryptjs';
import { supabaseAdmin } from '@/lib/supabase';

const CredentialsSchema = z.object({
    username: z.string().min(3, 'Username must be at least 3 characters.'),
    password: z.string().min(6, 'Password must be at least 6 characters.'),
});

export async function authenticate(
    prevState: string | undefined,
    formData: FormData,
) {
    try {
        await signIn('credentials', {
            username: formData.get('username'),
            password: formData.get('password'),
            redirect: false,
        });
        return null; // Success
    } catch (error) {
        if (isRedirectError(error)) {
            // signIn succeeded but threw a redirect — session cookie is set
            return null;
        }
        if (error instanceof AuthError) {
            switch (error.type) {
                case 'CredentialsSignin':
                    return 'Invalid credentials.';
                default:
                    return 'Something went wrong.';
            }
        }
        return 'Something went wrong.';
    }
}

export async function register(
    prevState: string | undefined,
    formData: FormData,
) {
    const data = Object.fromEntries(formData);
    const parsed = CredentialsSchema.safeParse(data);

    if (!parsed.success) {
        return 'Invalid input: ' + parsed.error.issues.map(e => e.message).join(', ');
    }

    const { username, password } = parsed.data;

    // Check if user exists
    const { data: existingUser } = await supabaseAdmin
        .from('Users')
        .select('id')
        .eq('username', username)
        .single();

    if (existingUser) {
        return 'Username already taken.';
    }

    const hashedPassword = await bcrypt.hash(password, 10);
    // userId is generated by Postgres (DEFAULT gen_random_uuid())
    const publicKey = formData.get('publicKey') as string;

    try {
        const { error } = await supabaseAdmin.from('Users').insert({
            username,
            password_hash: hashedPassword,
            public_key: publicKey,
            encrypted_vault: formData.get('encryptedVault') as string,
            vault_salt: formData.get('vaultSalt') as string
        });

        if (error) throw error;
    } catch (error) {
        console.error("Supabase Error:", error);
        return 'Database error: Failed to create user.';
    }

    // Return null = success. Client will handle signIn separately.
    return null;
}

// --- Profile Actions ---

export async function getUserProfileAction() {
    const session = await auth();
    if (!session?.user?.id) return { error: "Not authenticated" };

    const { data, error } = await supabaseAdmin
        .from('Users')
        .select('username, created_at, location, preferred_contact')
        .eq('id', session.user.id)
        .single();

    if (error || !data) return { error: "Failed to load profile" };
    return { profile: data };
}

export async function updateUserProfileAction(location: string, preferredContact: string) {
    const session = await auth();
    if (!session?.user?.id) return { error: "Not authenticated" };

    const { error } = await supabaseAdmin
        .from('Users')
        .update({
            location: location || null,
            preferred_contact: preferredContact || null,
        })
        .eq('id', session.user.id);

    if (error) return { error: "Failed to update profile" };
    return { success: true };
}

export async function deleteAccountAction() {
    const session = await auth();
    if (!session?.user?.id) return { error: "Not authenticated" };

    const { error } = await supabaseAdmin
        .from('Users')
        .delete()
        .eq('id', session.user.id);

    if (error) {
        console.error("Failed to delete account:", error);
        return { error: "Failed to delete account" };
    }
    return { success: true };
}

export async function getVaultAction(username: string) {
    const { data, error } = await supabaseAdmin
        .from('Users')
        .select('encrypted_vault, vault_salt, public_key')
        .eq('username', username)
        .single();

    if (error || !data) return { error: 'User not found' };

    return {
        encryptedVault: data.encrypted_vault,
        vaultSalt: data.vault_salt,
        publicKey: data.public_key
    };
}
