import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Privacy Policy",
    description: "uunn collects minimal data and encrypts everything end-to-end. Your messages, documents, and votes are never readable by us.",
};

export default function PrivacyPage() {
    return (
        <div className="container max-w-3xl mx-auto py-12 px-4">
            <h1 className="text-3xl font-bold mb-2">Privacy Policy</h1>
            <p className="text-sm text-muted-foreground mb-8">Effective April 7, 2026</p>

            <div className="space-y-8">
                <section>
                    <h2 className="text-xl font-bold mb-4">What We Collect (Very Little)</h2>
                    <p className="text-muted-foreground mb-4">
                        We practice data minimization. We only store what is absolutely necessary to deliver the service.
                    </p>
                    <ul className="list-disc pl-6 space-y-2 text-sm text-muted-foreground">
                        <li>Encrypted group metadata (to know which union you belong to).</li>
                        <li>Encrypted message metadata (timestamps, sender ID).</li>
                        <li>Account credentials (hashed passwords — we never store plaintext passwords).</li>
                    </ul>
                </section>

                <section>
                    <h2 className="text-xl font-bold mb-4">What We DON&apos;T Collect</h2>
                    <ul className="list-disc pl-6 space-y-2 text-sm text-muted-foreground">
                        <li><strong>Your Messages:</strong> Content is end-to-end encrypted. We cannot read it.</li>
                        <li><strong>Real Identity:</strong> We don&apos;t require legal names.</li>
                        <li><strong>Work Email:</strong> Not required. Sign up with just a username.</li>
                        <li><strong>IP Addresses:</strong> We do not log visitor IP addresses.</li>
                        <li><strong>Analytics:</strong> We do not use tracking cookies or analytics services.</li>
                    </ul>
                </section>

                <section>
                    <h2 className="text-xl font-bold mb-4">Local Storage & Cookies</h2>
                    <p className="text-muted-foreground mb-4">
                        uunn does not use tracking cookies. We use your browser&apos;s local storage and session storage solely for cryptographic purposes:
                    </p>
                    <ul className="list-disc pl-6 space-y-2 text-sm text-muted-foreground">
                        <li><strong>Session Storage:</strong> Your private encryption key is stored temporarily and cleared when you close the browser or log out.</li>
                        <li><strong>Authentication:</strong> A session token is used to keep you logged in. No third-party cookies are involved.</li>
                    </ul>
                </section>

                <section>
                    <h2 className="text-xl font-bold mb-4">Third-Party Services</h2>
                    <p className="text-muted-foreground mb-4">
                        uunn uses the following third-party services to operate:
                    </p>
                    <ul className="list-disc pl-6 space-y-2 text-sm text-muted-foreground">
                        <li><strong>Supabase:</strong> Database hosting. All sensitive content is encrypted before it reaches Supabase — they cannot read your messages or documents.</li>
                        <li><strong>Google Gemini:</strong> Optional AI-assisted document drafting. Used server-side only. No message content or personal data is sent to Google.</li>
                        <li><strong>Vercel:</strong> Application hosting. Standard web server logs may be generated by the hosting provider.</li>
                    </ul>
                </section>

                <section>
                    <h2 className="text-xl font-bold mb-4">Data Retention</h2>
                    <p className="text-muted-foreground mb-4">
                        Your data is stored for as long as your account exists. When you delete your account, all associated data — including memberships, messages, and documents — is permanently removed from our servers. We do not retain backup copies of deleted accounts.
                    </p>
                </section>

                <section>
                    <h2 className="text-xl font-bold mb-4">Your Rights</h2>
                    <p className="text-muted-foreground mb-4">
                        You have full control over your data.
                    </p>
                    <div className="p-4 border rounded-md">
                        <h3 className="font-semibold mb-2">Delete Account</h3>
                        <p className="text-xs text-muted-foreground">
                            Permanently remove all your data from our servers. You can delete your account at any time from your <a href="/settings" className="text-primary hover:underline">Profile Settings</a>.
                        </p>
                    </div>
                </section>

            </div>
        </div>
    );
}
